export const FONTS = [
  "Arial",
  "Arial Narrow",
  "Arial Narrow Bold",
  "Calibri",
  "Cambria",
  "Cochin",
  "Courier",
  "Courier New",
  "cursive",
  "fantasy",
  "Franklin Gothic Medium",
  "Geneva",
  "Georgia",
  "Gill Sans",
  "Gill Sans MT",
  "Haettenschweiler",
  "Helvetica",
  "Impact",
  "Inter",
  "Lucida Grande",
  "Lucida Sans",
  "Lucida Sans Regular",
  "Lucida Sans Unicode",
  "monospace",
  "Roboto",
  "sans-serif",
  "Segoe UI",
  "serif",
  "Tahoma",
  "Times",
  "Times New Roman",
  "Trebuchet MS",
  "Open Sans",
  "Verdana",
];

export { default } from "./font-select";
